### ISSUE TITLE
HOW TO UPLOAD PFD FILES?

### ISSUE THREAD

**Issue by mhpm** [kartoteket/vue-image-upload-resize#12]
can you help me please, how can i config for accept files like pdf, docs, image, etc?

**Comment by svale** [comment]
As of 2.0.4 (updated today) , you can set the file input to accept any file type you wish (e.g. `accept="application/pdf"` for PDFs), and the plugin will simply return any non-image file type directly as a File object. (See a list a file types [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types))

However, for uploads not requiring client size image resizing, I probably wouldn't use this plugin at all

I thought I had this fixed in 2.0.3, but the changes weren't propagated properly to the npm packages. Probably why you didn't get this working before - sorry!

**Comment by mhpm** [comment]
thank you my friend, sorry but i hafe another big problem, when i upload an image, there are 3 methods where the file is procesed: @input="setImage", @onUpload="startImageResize" ,@onComplete="endImageResize". but when i try to upload the same file again it does not pass for the 3 methods again, and i need it.  how can i clean programatically the file uploaded previewsly? please help!
